export const CHAT_CONSTANTS = {
  MAX_MESSAGE_WIDTH: '80%',
  BUBBLE_PADDING: 12,
  BUBBLE_BORDER_RADIUS: 20,
  MESSAGE_FONT_SIZE: 16,
  TIMESTAMP_FONT_SIZE: 12,
  MESSAGE_LINE_HEIGHT: 20,
  CONTAINER_MARGIN: {
    VERTICAL: 4,
    HORIZONTAL: 16,
  },
} as const; 